plugins:
  - "jekyll-github-metadata"
site.title: iam0day
name: iam0day
title: iam0day
author: iam0day
twitter_username: iam0day
github_username:  iam0day
seo_paginator_message: none
logo: favicon.ico
description: Fake developer, real vulnerability
theme: jekyll-theme-cayman
